# Generated by Django 4.0.1 on 2022-01-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chooseKey', models.IntegerField(null=True)),
                ('count', models.IntegerField(null=True)),
                ('grade', models.IntegerField(default=0)),
                ('keyType', models.IntegerField()),
                ('mainCategory', models.IntegerField()),
                ('mainKey', models.IntegerField()),
                ('name', models.TextField(max_length=200)),
                ('pricePeOne', models.IntegerField(null=True)),
                ('subCategory', models.IntegerField()),
                ('subKey', models.IntegerField()),
                ('totalTradeCount', models.IntegerField(null=True)),
                ('mainLabel', models.TextField(max_length=200)),
                ('subLabel', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
