# Generated by Django 4.0.1 on 2022-01-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropName', models.TextField(max_length=200)),
                ('dropValue', models.IntegerField()),
                ('dropCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GrindZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoneName', models.TextField(max_length=200)),
                ('persons', models.IntegerField()),
                ('drops', models.ManyToManyField(to='grind.Drop')),
            ],
        ),
    ]
